global:
  scrape_interval:     15s 
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'server'
    static_configs:
    - targets: ['kong-node-exporter:9100']
  - job_name: 'kong'
    scrape_interval: 5s
    static_configs:
      - targets: ['kong-gateway:8001']